/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Gustavo
 */
public class TelaCadastroUsuarioInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUsuarioInterna
     */
    public TelaCadastroUsuarioInterna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        pnlUserCadastro = new javax.swing.JPanel();
        lblUserCadastro = new javax.swing.JLabel();
        lblUserNome = new javax.swing.JLabel();
        lblUserSenha = new javax.swing.JLabel();
        lblUserConfSen = new javax.swing.JLabel();
        txtUserNome = new javax.swing.JTextField();
        txtUserSenha = new javax.swing.JTextField();
        txtUserConfSen = new javax.swing.JTextField();
        btnUserSalvar = new javax.swing.JButton();
        btnUserCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jTextField3.setText("jTextField3");

        setClosable(true);

        lblUserCadastro.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        lblUserCadastro.setText("CADASTRO DE USUÁRIO");

        lblUserNome.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblUserNome.setText("Nome de usuário:");

        lblUserSenha.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblUserSenha.setText("Senha:");

        lblUserConfSen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblUserConfSen.setText("Confirme a Senha:");

        txtUserNome.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        txtUserSenha.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        txtUserConfSen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        btnUserSalvar.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnUserSalvar.setText("Salvar");

        btnUserCancelar.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnUserCancelar.setText("Cancelar");

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserCadastroLayout = new javax.swing.GroupLayout(pnlUserCadastro);
        pnlUserCadastro.setLayout(pnlUserCadastroLayout);
        pnlUserCadastroLayout.setHorizontalGroup(
            pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserCadastroLayout.createSequentialGroup()
                .addGroup(pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserCadastroLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblUserCadastro))
                    .addGroup(pnlUserCadastroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserCadastroLayout.createSequentialGroup()
                                .addComponent(btnUserSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUserCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblUserNome)
                                .addComponent(lblUserSenha)
                                .addComponent(lblUserConfSen)
                                .addComponent(txtUserNome)
                                .addComponent(txtUserSenha)
                                .addComponent(txtUserConfSen, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnlUserCadastroLayout.setVerticalGroup(
            pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserCadastro)
                .addGap(18, 18, 18)
                .addComponent(lblUserNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUserSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserConfSen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserConfSen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlUserCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserCancelar)
                    .addComponent(btnUserSalvar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUserCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUserCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserCancelar;
    private javax.swing.JButton btnUserSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblUserCadastro;
    private javax.swing.JLabel lblUserConfSen;
    private javax.swing.JLabel lblUserNome;
    private javax.swing.JLabel lblUserSenha;
    private javax.swing.JPanel pnlUserCadastro;
    private javax.swing.JTextField txtUserConfSen;
    private javax.swing.JTextField txtUserNome;
    private javax.swing.JTextField txtUserSenha;
    // End of variables declaration//GEN-END:variables
}
